[package]
name = "mini-jabber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Serialization
serde = "1.*"
serde-xml-rs = "0.6.*"

# Errors
color-eyre = "0.6.*"

# Async
tokio = { version = "1.34.*", features = ["full"] }
tokio-tungstenite = "0.20.*"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
